### ISSUE TITLE
If a picklist is visible on a Tableau in the Navigator only the first 100 items in the picklist are returned.

### ISSUE THREAD

**Issue by NathanPoulton** [dickmans/plm-extensions#6]
This results in if an item displayed has a picklist field where the data is further in that the first 100 items it appears to be blank

**Comment by dickmans** [comment]
Hello Nathan, thank yo for reporting this issue. This is a known limitation. Please note that this package is not an official product and we cannot guarantee any support. This is why I will disable the Issue tab in this repository.
Nevertheless, if I find the time, I will fix this limitation. It was not of importance yet, fortunately.
Sven
